image: node:latest

before_script:
    - echo "$CI_REGISTRY_USER" 
    - echo "$CI_REGISTRY_PASSWORD" 
    - echo "$CI_REGISTRY" 
    - echo "$CI_REGISTRY_IMAGE"

stages:
    - production

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - cd erp-money
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=frontend-erp-money --api-key=ea8eaee0-d532-4799-952f-ae3ee05a456c
    only:
        - master
