image: node:latest

before_script:
    - echo "$CI_REGISTRY_USER" 
    - echo "$CI_REGISTRY_PASSWORD" 
    - echo "$CI_REGISTRY" 
    - echo "$CI_REGISTRY_IMAGE"

stages:
    - build_and_push_image
    - production

build_and_push_image:
    stage: build_and_push_image
    image: docker:latest
    tags:
        - gitlab-org-docker
    services:
        - docker:dind
    script:
        - cd erp-money
        - docker info
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    only:
        - master

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=frontend-erp-money --api-key=ea8eaee0-d532-4799-952f-ae3ee05a456c
    only:
        - master
